# Generated by Django 4.2.9 on 2024-08-01 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.CharField(max_length=100)),
                ("batch_start_date", models.DateTimeField(blank=True, null=True)),
                ("total_viable_cells", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_date", models.DateTimeField(blank=True, null=True)),
                ("total_viable_cells", models.FloatField(blank=True, null=True)),
                ("viable_cell_density", models.FloatField(blank=True, null=True)),
                ("cell_diameter", models.FloatField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.batch"
                    ),
                ),
            ],
        ),
    ]
