# Generated by Django 4.2.9 on 2024-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="editor_backup",
            field=models.TextField(default=""),
        ),
    ]
