# Generated by Django 4.2.9 on 2024-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="process_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
