# Generated by Django 4.2.9 on 2024-08-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_measurement_process_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="total_viable_cells",
        ),
        migrations.AddField(
            model_name="batch",
            name="harvest_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
