# Generated by Django 4.2.9 on 2024-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_remove_batch_total_viable_cells_batch_harvest_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="status",
            field=models.CharField(
                blank=True, default="Ongoing", max_length=100, null=True
            ),
        ),
    ]
