# Generated by Django 4.2.9 on 2024-08-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0004_batch_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phenotyping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_ops", models.CharField(max_length=100)),
                ("cd3", models.FloatField(blank=True, null=True)),
                ("cd8", models.FloatField(blank=True, null=True)),
                ("cd4", models.FloatField(blank=True, null=True)),
                ("cm", models.FloatField(blank=True, null=True)),
                ("naive", models.FloatField(blank=True, null=True)),
                ("effector", models.FloatField(blank=True, null=True)),
                ("em", models.FloatField(blank=True, null=True)),
                ("cd14", models.FloatField(blank=True, null=True)),
                ("cd19", models.FloatField(blank=True, null=True)),
                ("cd20", models.FloatField(blank=True, null=True)),
                ("cd56", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="measurement",
            name="phenotyping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapi.phenotyping",
            ),
        ),
    ]
