# Generated by Django 4.2.9 on 2024-08-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0005_phenotyping_measurement_phenotyping"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
