# Generated by Django 4.2.9 on 2024-08-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0006_batch_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="batch", name="data",),
        migrations.AddField(
            model_name="measurement",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
