# Generated by Django 4.2.9 on 2024-08-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0007_remove_batch_data_measurement_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="measurement", name="cell_diameter",),
        migrations.RemoveField(model_name="measurement", name="phenotyping",),
        migrations.RemoveField(model_name="measurement", name="process_time",),
        migrations.RemoveField(model_name="measurement", name="total_viable_cells",),
        migrations.RemoveField(model_name="measurement", name="viable_cell_density",),
    ]
