# Generated by Django 4.2.9 on 2024-08-22 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0008_remove_measurement_cell_diameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="phenotyping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapi.phenotyping",
            ),
        ),
    ]
