# Generated by Django 4.2.9 on 2024-08-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0009_measurement_phenotyping"),
    ]

    operations = [
        migrations.RemoveField(model_name="measurement", name="phenotyping",),
        migrations.AddField(
            model_name="batch",
            name="tags",
            field=models.JSONField(blank=True, default={"tags": []}, null=True),
        ),
        migrations.DeleteModel(name="Phenotyping",),
    ]
