# Generated by Django 4.2.9 on 2024-08-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0010_remove_measurement_phenotyping_batch_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
