# Generated by Django 4.2.9 on 2024-08-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0011_alter_batch_tags"),
    ]

    operations = [
        migrations.RenameField(model_name="batch", old_name="tags", new_name="data",),
    ]
