# Generated by Django 4.2.9 on 2024-08-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0012_rename_tags_batch_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="lot_number",
            field=models.CharField(default="None Provided", max_length=100),
        ),
    ]
