# Generated by Django 4.2.9 on 2024-08-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0013_measurement_lot_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="InactiveColumns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
