# Generated by Django 4.2.9 on 2024-08-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0014_inactivecolumns"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="phenotyping_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="flagged_columns",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
