# Generated by Django 4.2.9 on 2024-08-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0015_batch_phenotyping_data_measurement_flagged_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="qc_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
