# Generated by Django 4.2.9 on 2024-07-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_date", models.DateField(blank=True, null=True)),
                ("total_viable_cells", models.IntegerField(blank=True, null=True)),
                ("viable_cell_density", models.FloatField(blank=True, null=True)),
                ("cell_diameter", models.FloatField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.batch"
                    ),
                ),
            ],
        ),
    ]
