# Generated by Django 5.0.1 on 2024-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0002_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="measurement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
