# Generated by Django 4.2.9 on 2024-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_alter_measurement_measurement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
