# Generated by Django 4.2.9 on 2024-07-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0004_alter_batch_batch_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="total_viable_cells",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="total_viable_cells",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
